server:
  port: 9095
spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
resilience4j:
  circuitbreaker:
    instances:
      userServiceBreaker:
      slidingWindowType: COUNT_BASED # 10 derniers appels
      slidingWindowSize: 5 # fenêtre de 5 appels
      failureRateThreshold: 50 # 50% d'échecs => OPEN
      waitDurationInOpenState: 5s # rester OPEN 5 sec
      permittedNumberOfCallsInHalfOpenState: 2 # 2 tests
      automaticTransitionFromOpenToHalfOpenEnabled: true
      minimumNumberOfCalls: 5
      myRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.lang.RuntimeException
      myTimeout:
        timeout-duration: 1s  
